export enum ARIAPreDefinedRoles {
    Alert  ='alert', // A message with an alert or error information.
    AlertDialog = 'alertdialog', // A separate window with an alert or error information.
    Application = 'application', // A software unit executing a set of tasks for its users.
    Button ='button', // Allows for user-triggered actions.
    Checkbox = 'checkbox', // A control that has three possible values, (true, false, mixed).
    ColumnHeader = 'columnheader', // A table cell containing header information for a column.
    Combobox = 'combobox', // Combobox is a presentation of a select, where users can type to locate a selected item.
    Description = 'description', // Descriptive content for a page element which references this element via describedby.
    Dialog = 'dialog', // A dialog is a small application window that sits above the application and is designed to interrupt the current processing of an application in order to prompt the user to enter information or require a response.
    Directory = 'directory', // A list of references to members of a single group.
    Document = 'document', // Content that contains related information, such as a book.
    Grid = 'grid', // A grid contains cells of tabular data arranged in rows and columns (e.g., a table).
    GridCell = 'gridcell', // A gridcell is a table cell in a grid. Gridcells may be active, editable, and selectable. Cells may have relationships such as controls to address the application of functional relationships.
    group = 'group', // A group is a section of user interface objects which would not be included in a page summary or table of contents by an assistive technology. See region for sections of user interface objects that should be included in a page summary or table of contents.
    Heading = 'heading', // A heading for a section of the page.
    Img = 'img', // An img is a container for a collection elements that form an image.
    Link = 'link', // Interactive reference to a resource (note, that in XHTML 2.0 any element can have an href attribute and thus be a link)
    List = 'list', // Group of non-interactive list items. Lists contain children whose role is listitem.
    ListBox = 'listbox', // A list box is a widget that allows the user to select one or more items from a list. Items within the list are static and may contain images. List boxes contain children whose role is option.
    ListItem = 'listitem', // A single item in a list.
    Log = 'log', // A region where new information is added and old information may disappear such as chat logs, messaging, game log or an error log. In contrast to other regions, in this role there is a relationship between the arrival of new items in the log and the reading order. The log contains a meaningful sequence and new information is added only to the end of the log, not at arbitrary points.
    Marquee = 'marquee', // A marquee is used to scroll text across the page.
    Menu = 'menu', // Offers a list of choices to the user.
    Menubar = 'menubar', // A menubar is a container of menu items. Each menu item may activate a new sub-menu. Navigation behavior should be similar to the typical menu bar graphical user interface.
    Menuitem = 'menuitem', // A link in a menu. This is an option in a group of choices contained in a menu.
    MenuItemCheckbox = 'menuitemcheckbox', // Defines a menuitem which is checkable (tri-state).
    MenuItemRadio = 'menuitemradio', // Indicates a menu item which is part of a group of menuitemradio roles.
    Option = 'option', // A selectable item in a list represented by a select.
    Presentation = 'presentation', // An element whose role is presentational does not need to be mapped to the accessibility API.
    ProgressBar = 'progressbar', // Used by applications for tasks that take a long time to execute, to show the execution progress.
    Radio = 'radio', // A radio is an option in single-select list. Only one radio control in a radiogroup can be selected at the same time.
    RadioGroup = 'radiogroup', // A group of radio controls.
    Region = 'region', // Region is a large perceivable section on the web page.
    Row = 'row', // A row of table cells.
    RowHeader = 'rowheader', // A table cell containing header information for a row.
    Separator = 'separator', // A line or bar that separates and distinguishes sections of content.
    Slider = 'slider', // A user input where the user selects an input in a given range. This form of range expects an analog keyboard interface.
    Spinutton = 'spinbutton', // A form of Range that expects a user selecting from discrete choices.
    Status = 'status', // This is a container for process advisory information to give feedback to the user.
    Tab = 'tab', // A header for a tabpanel.
    TabList = 'tablist', // A list of tabs, which are references to tabpanels.
    TabPanel = 'tabpanel', // Tabpanel is a container for the resources associated with a tab.
    TextBox = 'textbox', // Inputs that allow free-form text as their value.
    Timer = 'timer', // A numerical counter which indicates an amount of elapsed time from a start point, or the time remaining until an end point.
    Toolbar = 'toolbar', // A toolbar is a collection of commonly used functions represented in compact visual form.
    Tooltip = 'tooltip', // A popup that displays a description for an element when a user passes over or rests on that element. Supplement to the normal tooltip processing of the user agent.
    Tree = 'tree', // A form of a list having groups inside groups, where sub trees can be collapsed and expanded.
    TreeGrid = 'treegrid', // A grid whose rows can be expanded and collapsed in the same manner as for a tree.
    TreeItem = 'treeitem', // An option item of a tree. This is an element within a tree that may be expanded or collapsed.
}
